# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven build Verify

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-distribution:
        required: true
        type: string
        default: 'temurin'
      
    secrets:
      MAVEN_S3_USER:
        required: true
      MAVEN_S3_PASSWORD:
        required: true 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        java-version:  ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
          
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
            
    - uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{"id":"awss3_snapshots","name":"AWS S3 Snapshots","url":"s3://repository.maven/snapshots","releases":{"enabled":"false"},"snapshots":{"enabled":"true"}},{"id":"awss3_releases","name":"AWS S3 Releases","url":"s3://repository.maven/releases","releases":{"enabled":"true"},"snapshots":{"enabled":"false"}}]'
        servers: '[{ "id": "awss3_snapshots", "username": "${env.MAVEN_S3_USER}", "password": "${env.MAVEN_S3_PASSWORD}" }, { "id": "awss3_releases", "username": "${env.MAVEN_S3_USER}", "password": "${env.MAVEN_S3_PASSWORD}" }]'
        output_file: .m2/settings.xml
          
    - name: print settings.xml
      run: cat .m2/settings.xml
    
    - name: Build with Maven on Java 17
      run: mvn -B verify --file pom.xml --settings .m2/settings.xml
      env:
        MAVEN_S3_USER: ${{ secrets.MAVEN_S3_USER }}
        MAVEN_S3_PASSWORD: ${{ secrets.MAVEN_S3_PASSWORD }}